### ISSUE TITLE
Specify glob for automatic sections

### ISSUE THREAD

**Issue by Quenty** [UpliftGames/moonwave#101]
In a mono-repo scenario code may already be organized via folders/sections. Being able to specify a glob that will capture section roots would be good, as it would allow these sections to be defined automatically in the API section. For example,

```
packages/**
```
Would group each section via a package folder structure like this.

**Comment by evaera** [comment]
This has already been implemented in 5fdfaaa1c338105b272393d00fda72fca3932534 :D

**Comment by Quenty** [comment]
So speedy! Thank you!
