### ISSUE TITLE
Ability to specify inherited class from another class

### ISSUE THREAD

**Issue by Quenty** [UpliftGames/moonwave#102]
It would be good to specify inherited properties on a class. Very important API members, like :Destroy() are inherited from certain classes and currently there's no way to specify this inherited model.

Even better would be automatic detection, however, I do not think this is easy or even possible with custom module loading systems right now.

https://robloxapi.github.io/ref/class/Frame.html

**Comment by evaera** [comment]
Duplicate of #52?
