### ISSUE TITLE
String singletons throwing errors if initialized in Types

### ISSUE THREAD

**Issue by leoyulee** [UpliftGames/moonwave#112]
Any string singleton made within a Luau Type will throw an unexpected token.

Section throwing error:
![image](https://user-images.githubusercontent.com/56608247/161487509-3b673f48-a9c3-4f3e-8ff5-0810ff169a2c.png)

Error output:
![image](https://user-images.githubusercontent.com/56608247/161487606-227c5f25-4df8-480e-a4dd-487dc482830e.png)

Related Discord discussion:
https://discord.com/channels/385151591524597761/894395472582676502/959873911728783381

**Comment by evaera** [comment]
Closed in 320029558df4a15444af76d14e9468979e52a463
