### ISSUE TITLE
No way to ignore node_modules

### ISSUE THREAD

**Issue by Quenty** [UpliftGames/moonwave#74]
I have some very deep node_modules that are found here:

![image](https://user-images.githubusercontent.com/1774409/138504372-f01f1ee8-4df3-468c-a901-c3cf23bc759c.png)

I need to tell moonwave to not extract from these filepaths since they include 3rd party content and/or file links too deep for moonwave to support.

**Comment by evaera** [comment]
Superseding this issue with issue #83.
