### ISSUE TITLE
API page throwing `Uncaught TypeError: sidebarClassNames[0] is undefined`

### ISSUE THREAD

**Issue by vocksel** [UpliftGames/moonwave#99]
I have just brought Moonwave into a new project and I am getting the following errors:

![firefox_2021-12-24_11-44-26](https://user-images.githubusercontent.com/3081936/147370559-41e1d755-baca-4726-afd5-bf9403d049d0.png)

From the looks of other repos I should be including a moonwave.toml file, but the [intro documentatin](https://upliftgames.github.io/moonwave/docs/intro) does not seem to mention this. Not sure if this is a bug or just improper configuration that needs supporting docs for

I am running Moonwave ^0.2.14 and Node 14.17.2.

### Repro steps

1. `npm init -y`
2. `npm install --save-dev moonwave`
3. Include a new command in `package.json` to run Moonwave:
    ```
    "scripts": {
      "serve": "moonwave dev",
    },
    ```
4. `npm run serve`
5. Navigate to https://localhost:3000/api

**Comment by evaera** [comment]
This happens when you don't have any API pages.

**Comment by vocksel** [comment]
Good to know! I think this was ocurring because I had an edge case like #98 where I had included a doc comment properly but it was not being picked up. Issue is resolved on my end
